"""Added Cookie model

Revision ID: 69c929589ae3
Revises: b0c549982f8a
Create Date: 2016-07-14 17:18:13.838000

"""

# revision identifiers, used by Alembic.
revision = '69c929589ae3'
down_revision = 'b0c549982f8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_cookies',
    sa.Column('cookie_id', sa.Integer(), nullable=False),
    sa.Column('cookie_name', sa.String(length=50), nullable=True),
    sa.Column('cookie_recipe_url', sa.String(length=255), nullable=True),
    sa.Column('cookie_sku', sa.String(length=55), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('cookie_id')
    )
    op.create_index(op.f('ix_new_cookies_cookie_name'), 'new_cookies', ['cookie_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_cookies_cookie_name'), table_name='new_cookies')
    op.drop_table('new_cookies')
    ### end Alembic commands ###
